### ISSUE TITLE
看了图，你注销应该是打算每个应用自己处理，不知道有没有全局注销？

### ISSUE THREAD

**Issue by dengji85** [cdk8s/tkey-issues#3]

**Comment by cdk8s-zelda** [comment]
关于单点登出（单点退出、单点注销）的话题我在这里有进行了说明，你可以看下：
https://github.com/cdk8s/tkey-docs/blob/master/faq/README.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89%E5%8D%95%E7%82%B9%E7%99%BB%E5%87%BA
